### ISSUE TITLE
Some terms need explanation

### ISSUE THREAD

**Issue by wgy8283335** [apache/incubator-shardingsphere-doc#113]
After read documnet in 
https://shardingsphere.apache.org/document/legacy/3.x/document/cn/features/sharding/principle/route/
some terms need explanation.
For example:广播路由,全库路由，全库表路由，全实例路由，单播路由，阻断路由。
What is difference among them?

**Comment by terrymanu** [comment]
Could you provide pull request?

**Comment by wgy8283335** [comment]
Yes, I could. Let me start from Chinese, ok? Then after English.

**Comment by terrymanu** [comment]
Fine, we can start from Chinese and then translate them

**Comment by wgy8283335** [comment]
@terrymanu. Thank you. Now, I'd like to start to translate them.

**Comment by terrymanu** [comment]
Any other update or can we close this issue?
