### ISSUE TITLE
hint-example related page could not be found.

### ISSUE THREAD

**Issue by wgy8283335** [apache/incubator-shardingsphere-doc#133]
In page 'https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/usage/hint/', there is a hint-example link. 
After click on it, open a new page with link 'https://github.com/sharding-sphere-example/tree/dev/sharding-jdbc-example/hint-example'. 
But, it shows 'Page not found'.

**Comment by cherrylzhao** [comment]
OK，I'll fix it later
