### ISSUE TITLE
Write document for process generated key and the SQL rewrite result

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere-doc#243]
ShardingSphere can process 4 types of SQL (assume id is auto_imcrement): 

- INSERT (id, name) VALUES (1, "xxx")    =>    
not change
- INSERT (name) VALUES ("xxx")    =>    
INSERT (name, id) VALUES ("xxx", ?)
- INSERT VALUES (1, "xxx")   =>    
INSERT (id, name) VALUES (1, "xxx")
- INSERT VALUES ("xxx")   =>    
INSERT (name, id) VALUES ("xxx", ?)

This feature need to documentation more details.

And we need to add more document for `INSERT SET` and `INSERT for multiple VALUES`

**Comment by tuohai666** [comment]
Docs had been transferred to incubator-shardingsphere/docs.
