### ISSUE TITLE
add doc for proxy-hint feature

### ISSUE THREAD

**Issue by cherrylzhao** [apache/incubator-shardingsphere-doc#247]
- [x] [sctl-sharding-proxy-control-language-cn](https://github.com/apache/incubator-shardingsphere-doc/blob/master/document/current/content/manual/sharding-proxy/usage.cn.md#sctl-sharding-proxy-control-language)
- [ ] [sctl-sharding-proxy-control-language-en](https://github.com/apache/incubator-shardingsphere-doc/blob/master/document/current/content/manual/sharding-proxy/usage.en.md#sctl-sharding-proxy-control-language)

**Comment by betterjava** [comment]
- [ ] sctl-sharding-proxy-control-language-cn
  - [ ] sctl-sharding-proxy-control-update
  - [ ] sctl-sharding-proxy-control-query
- [ ] sctl-sharding-proxy-control-language-en
  - [ ] sctl-sharding-proxy-control-update
  - [ ] sctl-sharding-proxy-control-query
