### ISSUE TITLE
Add document for Nacos as reg center

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere-doc#274]
We are support Nacos as reg center now. 
FIY: https://github.com/apache/incubator-shardingsphere/pull/3150
 We need a document for this

**Comment by huangjian888** [comment]
How should I submit the Nacos Configuration Center document? Submit demo?

**Comment by terrymanu** [comment]
you may pull request for file:
https://github.com/apache/incubator-shardingsphere-doc/blob/master/document/current/content/features/orchestration/supported-registry-repo.en.md

and

https://github.com/apache/incubator-shardingsphere-doc/blob/master/document/current/content/features/orchestration/supported-registry-repo.cn.md

**Comment by huangjian888** [comment]
ok!
