### ISSUE TITLE
Let menu of document collapsible

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-shardingsphere-doc#319]
We use Hugo to generate the document website.
The menu of current website cannot collapse, all of sub-menus are displayed which is bad reading experience.

Is there anybody want to investigate about hugo to generate collapsible menu? 
FYI: https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu

**Comment by harvies** [comment]
I will try it.

**Comment by orangeyts** [comment]
I will research

**Comment by terrymanu** [comment]
#323 use JQuery to fix this issue, but not use hugo style.
So do you think we need to continually research it?

**Comment by orangeyts** [comment]
you mean just use JQuery turning?

**Comment by terrymanu** [comment]
So, maybe we can keep it there and close this issue?

**Comment by orangeyts** [comment]
is it tested? 
if it is work,I think should close.

**Comment by terrymanu** [comment]
It is fine now. I just closed this issue.

**Comment by terrymanu** [comment]
I just revert the previous changes because the collapsible is conflict with show page original content.

**Comment by terrymanu** [comment]
We need to add (+) and (-) button to control collapsible behaviour and if user click the title should go to this url.

**Comment by wqzwh** [comment]
I also pay attention

**Comment by lazeyliu** [comment]
I had commited a pr #347  with +- style
