### ISSUE TITLE
Make the document contribution more clear

### ISSUE THREAD

**Issue by geomonlin** [apache/incubator-shardingsphere-doc#321]
This is a link to the document contribution Guide 
   https://shardingsphere.apache.org/community/cn/contribute/document-contributor/

**Comment by taojintianxia** [comment]
so what kind of info you want get from the document since it's not "clear"

**Comment by geomonlin** [comment]
> so what kind of info you want get from the document since it's not "clear"

I once submitted this pull. Can you see what's wrong  https://github.com/apache/incubator-shardingsphere-doc/pull/326
