### ISSUE TITLE
按照官网3.0.0的配置手册，配置3.1.0最新release版，会报错

### ISSUE THREAD

**Issue by KevinTHU** [apache/incubator-shardingsphere-doc#59]
3.1.0好像没有autoCommit这个配置字段了，如果配置文件中有该字段，启动程序会报错。辛苦了解下。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by KevinTHU** [comment]
ok, I will rewrite this issue. But as a suggestion, a readme about issue language may be cool.
